### ISSUE TITLE
 Multi-Source Transfer

### ISSUE THREAD

**Issue by jinxuan777** [alinlab/L2T-ww#2]
hi, @hankook  thx for nice work~but I can not find code for Experiments on Multi-Source Transfer, could you share it?

**Comment by hankook** [comment]
Thanks for your interest in our work. We currently have no plan for uploading the code, but here we briefly introduce how to implement multi-source transfer: (1) create `WeightNetwork`, `LossWeightNetwork` and `FeatureMatching` instances per each teacher (source) network; (2) Modify the lists of parameters in optimizer and meta-optimizer; (3) In `inner_objective`, modify `matching_loss` as the summation of all matching losses from all teacher networks.
