### ISSUE TITLE
about folder */split/

### ISSUE THREAD

**Issue by WHUzhusihan96** [alinlab/L2T-ww#3]
How did you get the file like dog-test,dota-train and dot-val?
What do they represent for?
How to get it or are there any files related to other data sets？
thanks a lot!

**Comment by jnhwkim** [comment]
I assume that you can create those files with `torch.save()` in PyTorch. Each file has tuples, the first element indicates ~~the split indices (usually just a number sequence)~~ and the second and the last element indicates (randomly chosen for the split) the indices with regard to training samples.

I cannot find what percent is used for validation in the paper for each dataset, I believe randomly sampled 20% of validation should perform a similar result.

**Comment by hankook** [comment]
As @jnhwkim mentioned, you can load the split file using `torch.load()`. The object is a tuple. the first one is the list of classes and the second one is the list of sample indices.

We sampled 10% (class-balanced) training samples for validation.
