### ISSUE TITLE
how  can i transfer to object detection model like faster-rcnn?

### ISSUE THREAD

**Issue by Xiao-YiZi** [alinlab/L2T-ww#9]

**Comment by hankook** [comment]
Thank you for your interest and interesting question!

Our method (L2T-ww) is designed for transferring knowledge of hidden layers (e.g., feature maps for CNNs) between source and target networks. Therefore, as you suggested, one can use an object detection model as a target network. Specifically, the model often has a CNN backbone (e.g., ResNet), so you can apply our method between feature maps of a pre-trained CNN (source) and the backbone (target). In this case, the original loss (L_org in our paper) should be a detection loss.

**Comment by Xiao-YiZi** [comment]
> Thank you for your interest and interesting question!
> 
> Our method (L2T-ww) is designed for transferring knowledge of hidden layers (e.g., feature maps for CNNs) between source and target networks. Therefore, as you suggested, one can use an object detection model as a target network. Specifically, the model often has a CNN backbone (e.g., ResNet), so you can apply our method between feature maps of a pre-trained CNN (source) and the backbone (target). In this case, the original loss (L_org in our paper) should be a detection loss.

Thank you very much for your reply, i will try if it works
